name: Sync Fork with Upstream

on:
  schedule:
    # Läuft jeden Tag um Mitternacht (UTC)
    - cron: '0 0 * * *'
  # Erlaubt auch das manuelle Starten über den "Actions"-Tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run GitHub Sync Fork Action
        uses: tgymnich/fork-sync-action@v1.9
        with:
          owner: open-noodle
          repo: gallery
          head: main      # Passe das an, falls der Standard-Branch des Originals anders heißt (z.B. master)
          base: main      # Der Branch in deinem Fork, der aktualisiert werden soll
          token: ${{ secrets.GITHUB_TOKEN }}
